apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
  namespace: prod
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-svc:3306/petclinic"
  SPRING_PROFILES_ACTIVE: "mysql"
