apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app-deployment
  name: app-svc
  namespace: prod
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app: app-deployment
status:
  loadBalancer: {}