ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: necipulusoy.com
      paths:
        - path: /
          pathType: Prefix



configmap:
  name: application-configmap
  data: 
    SPRING_JPA_HIBERNATE_DDL_AUTO: "update" 
    SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-svc:3306/petclinic" 
    SPRING_PROFILES_ACTIVE: "mysql"




hpa:
  enabled: true
  maxReplicas: 3  
  minReplicas: 2  
  targetCPUUtilizationPercentage: 60  




deployment:
  name: application
  replicaCount: 1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - app-deployment
          topologyKey: "kubernetes.io/hostname"  
  securityContext:
    runAsUser: 33
    runAsNonRoot: true
  image:
    repository: "necipulusoyy9120/spring-petclinic-app"
    tag: "fa4ee80" 
  containerName: "deployment"
  podSecurityContext:
    allowPrivilegeEscalation: false
  livenessProbe:
    httpGet:
    initialDelaySeconds: 60
    periodSeconds: 20
  resources:
    limits:
      memory: "1Gi"
      cpu: "750m"
    requests:
      memory: "512Mi"
      cpu: "500m"



serviceAccount:
  name: application-sa
  automountServiceAccountToken: false 




secret:
  name: application-secret
  data:
    SPRING_DATASOURCE_USERNAME: "petclinic"  
    SPRING_DATASOURCE_PASSWORD: "petclinic"  




service:
  name: application-service
  type: NodePort  
  port: 8080  
  protocol: TCP        
  targetPort: 8080    
  nodePort: 30001

