name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Specify the main branch
  workflow_dispatch:   # Configuration for manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # Step 1: Fetch the latest code from the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      # Step 2: Set up Docker Buildx

    - name: Build Docker image with SHA tag
      run: |
        TAG=$(echo "${{ github.sha }}" | cut -c1-7)  # Get the first 7 characters of the SHA
        echo "TAG=$TAG" >> $GITHUB_ENV
        docker build -t necipulusoyy9120/spring-petclinic-app:$TAG -f application/Dockerfile application/
      # Step 3: Build the Docker image with the SHA tag

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
       # Step 4: Log in to Docker Hub

    - name: Push Docker image to Docker Hub
      run: |
        docker push necipulusoyy9120/spring-petclinic-app:$TAG
      # Step 5: Push the created Docker image to Docker Hub

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube  
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config  
        chmod 600 $HOME/.kube/config  
        kubectl get nodes
      # Step 6: Configure Kubeconfig

    - name: Update image tag in values.yaml
      run: |
        sed -i "s|tag: \".*\"|tag: \"$TAG\"|g" helm/values.yaml
      # Step 7: Update the image tag in values.yaml with the new SHA tag

    - name: Deploy to Kubernetes Cluster
      run: |
        helm upgrade --install helm ./helm -n prod
      # Step 8: Deploy the updated Helm chart to the Kubernetes cluster










