name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
    paths:
      - 'src/**'
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
     

    - name: Build Docker image with SHA tag
      run: |
        TAG=$(echo "${{ github.sha }}" | cut -c1-7)  
        echo "TAG=$TAG" >> $GITHUB_ENV
        docker build -t necipulusoyy9120/spring-petclinic-app:$TAG -f application/Dockerfile application/
      

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
     

    - name: Push Docker image to Docker Hub
      run: |
        docker push necipulusoyy9120/spring-petclinic-app:$TAG
      

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube  
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config  
        chmod 600 $HOME/.kube/config  
        kubectl get nodes
      

    - name: Update image tag in values.yaml
      run: |
        sed -i "s|tag: \".*\"|tag: \"$TAG\"|g" helm/values.yaml
      

    - name: Commit and push updated values.yaml
      run: |
        git config --global user.email "necipulusoyy@gmail.com"  
        git config --global user.name "necipulusoy"  
        git add helm/values.yaml  
        git commit -m "Update image tag to $TAG"  
        git pull origin main --rebase
        git push origin main  # Push the changes to the main branch

    - name: Deploy to Kubernetes Cluster
      run: |
        helm upgrade --install helm ./helm -n prod
     










