apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      serviceAccountName: mysql-sa
      automountServiceAccountToken: false
      volumes:
      # - name: local-storage
      - name: mysql-pv-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - image: mysql:8.0
        name: mysql
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: "/var/lib/mysql"
         # name: local-storage
          name: mysql-pv-storage
        envFrom:
        - secretRef:
            name: mysql-secret
        resources: 
          limits:
            memory: 750Mi
            cpu: 750m
          requests:
            memory: 500Mi
            cpu: 500m  





